package com.swing.training.enums;

/**
 * Enums for actions in controllers
 * 
 * @author SDhananjaya
 * 
 */
public enum Actions {

	PRESCRIPTION_LOAD_TABLE_DATA, PRESCRIPTION_PRINT, PRESCRIPTION_DELETE, PRESCRIPTION_LOAD_SELECTED_TABLE_DATA, PRESCRIPTION_CLEAR_INPUTS, PRESCRIPTION_LOAD_DRUGS, PRESCRIPTION_SAVE_ACTION, PRESCRIPTION_SEARCH_FROM_CRITERIA,

	PATIENT_LOAD_TABLE_DATA, PATIENT_PRINT, PATIENT_SAVE_ACTION, PATIENT_CLEAR_INPUTS, PATIENT_LOAD_SELECTED_TABLE_DATA, PATIENT_DELETE, PATIENT_SEARCH_FROM_CRITERIA,

	EMPLOYE_SAVE_ACTION, EMPLOYE_CLEAR_INPUTS, EMPLOYE_LOAD_TABLE_DATA, EMPLOYE_LOAD_SELECTED_TABLE_DATA, EMPLOYE_DELETE, EMPLOYE_SEARCH_FROM_CRITERIA,

	DRUG_SAVE_ACTION, DRUG_CLEAR_INPUTS, DRUG_LOAD_TABLE_DATA, DRUG_LOAD_SELECTED_TABLE_DATA, DRUG_DELETE, DRUG_SEARCH_FROM_CRITERIA;
}
